Update to 19.1.1 and sync changes with 18.1.8-2

diff --git a/build/llvm19-opt/PKGBUILD b/build/llvm19-opt/PKGBUILD
--- a/build/llvm19-opt/PKGBUILD
+++ b/build/llvm19-opt/PKGBUILD
@@ -18,7 +18,7 @@
 # Contributor: Tomas Wilhelmsson <tomas.wilhelmsson@gmail.com>
 
 pkgname=llvm19-opt
-_pkgver=19.1.0
+_pkgver=19.1.1
 pkgver=${_pkgver/-/_}
 pkgrel=1
 epoch=1
@@ -27,6 +27,7 @@ arch=('x86_64')
 url='https://llvm.org/'
 license=('Apache-2.0 WITH LLVM-exception')
 depends=(
+    'curl' 'libcurl.so'
     'gcc-libs'
     'glibc'
     'libedit' 'libedit.so'
@@ -35,6 +36,7 @@ depends=(
     'lua53'
     'ncurses' 'libncursesw.so' 'libpanelw.so'
     'perl'
+    'python'
     'xz' 'liblzma.so'
     'z3' 'libz3.so'
     'zlib' 'libz.so'
@@ -43,15 +45,10 @@ depends=(
 makedepends=(
     'cmake'
     'jsoncpp'
-    'lldb'
     'ninja'
     'ocl-icd'
     'opencl-headers'
-    'python-myst-parser'
-    'python-recommonmark'
     'python-setuptools'
-    'python-six'
-    'python-sphinx-automodapi'
     'swig'
 )
 checkdepends=(
@@ -59,8 +56,13 @@ checkdepends=(
     'python-psutil'
 )
 optdepends=(
-    'openmp: OpenMP support in clang with -fopenmp'
-    'python: for scan-view and git-clang-format'
+    'cuda: for OpenMP offloading to NVIDIA GPUs'
+    'hsa-rocr: for OpenMP offloading to AMD GPUs'
+    'python-guppy3: for opt-stats tool to show memory consumption'
+    'python-psutil: for LLVM Integrated Tester'
+    'python-pygments: for opt-viewer module'
+    'python-yaml: for opt-viewer module'
+    'sublime-text: for clang-format-sublime tool'
 )
 _major=${pkgver%%.*}
 provides=(
@@ -71,6 +73,7 @@ provides=(
     "lldb${_major}"
     "${pkgname%-opt}"
     "llvm${_major}-libs"
+    "openmp${_major}"
     "polly${_major}"
 )
 options=(
@@ -78,22 +81,25 @@ options=(
     '!lto'  # use ThinLTO instead
 )
 source=("https://github.com/llvm/llvm-project/releases/download/llvmorg-${_pkgver}/llvm-project-${_pkgver}.src.tar.xz"{,.sig}
-        'llvm-config.h')
-sha384sums=('db4fb8e59a28154832b8b2f054112626bd5a6acacb6b06a94658b3b401a5bafe89deffa5f4ad8f57307d74b9d9741b65'
+        '0201-enable-fstack-protector-strong-by-default.patch')
+sha384sums=('44cfd82b41fa490191b58898c3d09f7a4472f479c21e1e66653e6e6c467a1fd1b1fbab4cbc0cb251597ad32aa8bb78d9'
             'SKIP'
-            '3065a1f344a5a5bebeb0fd9fcc95bb325ebf63b20d9871d0f49bfbfd7a5434e3d5e8bdadac5a2d8033bb7fe2ebe3d7bb')
-b2sums=('972d028599006d528acdb0ff107b30af8bef247a0f174991646d07f0a47e7d237a5a1700ae668a9f4496295535d688eeeebe550669e78b0775aaab044f5b268e'
+            '1bf9730ada53600dcc26bef851b670ac52a05aaf9b77791f6a530aa5285f642195e990a4573da06f78edc680ae7df58a')
+b2sums=('7c9250f99c8e5ae2097e89269ebf5bfdfb0fba8f67ab934377d24030c985013fe5475d0c9bd6d60a679e169772ad1723bc6e44ff9e4c7aed5627b9f1f1a2477a'
         'SKIP'
-        'c7e56bfbb9983bc30977fed8d6e028d007dcce2bce03e91c38070fa4d5eb261919ab85f77a150cc31a857195586922b7bafb43070555da0194846fd1f6d1f515')
+        '5e3e949867d6e3e1b78e2b24a75192058020b095b402de452e2611ff9a7b9bccbf370d841d987b331cad06fe4cc23ea0ad31b21c5e84f0a3f5055d3761621463')
 validpgpkeys=('474E22316ABF4785A88C6E8EA2C794A986419D8A'   # Tom Stellard <tstellar@redhat.com>
               'D574BD5D1D0E98895E3BF90044F2485E45D59042')  # Tobias Hieta <tobias@hieta.se>
+
+# TODO: Avoid adding LLVM into checkdepends just for LIT
+[[ -n ${_bootstrap} ]] || checkdepends+=('llvm')
 
 # Utilizing LLVM_DISTRIBUTION_COMPONENTS to avoid
 # installing static libraries; inspired by Gentoo
 _get_distribution_components() {
     local target
-    ninja -t targets | grep -Po 'install-\K.*(?=-stripped:)' | while read -r target; do
-        case $target in
+    ninja -C build-llvm -t targets | grep -Po 'install-\K.*(?=-stripped:)' | while read -r target; do
+        case "${target}" in
             clang-libraries|llvm-libraries|distribution)
                 continue
                 ;;
@@ -111,16 +117,13 @@ _get_distribution_components() {
             llvm-exegesis)
                 continue
                 ;;
-            clang-tidy-headers)
-                continue
-                ;;
             clang|clangd|clang-*)
                 ;;
             clang*|findAllSymbols)
                 continue
                 ;;
         esac
-        echo $target
+        echo "${target}"
     done
 }
 
@@ -141,38 +144,54 @@ EOF
 }
 
 prepare() {
+    cd "llvm-project-${_pkgver}.src"
+
+    # [extra]/clang additions: enable -fstack-protector-strong by default
+    patch -p1 <../0201-enable-fstack-protector-strong-by-default.patch
+
+    # Remove CMake find module for zstd; breaks if out of sync with upstream zstd
+    rm llvm/cmake/modules/Findzstd.cmake
+
     # Attempt to convert script to Python 3
     2to3 -w -n --no-diffs \
-        "${srcdir}/llvm-project-${_pkgver}.src/clang-tools-extra/clang-include-fixer/find-all-symbols/tool/run-find-all-symbols.py"
+        clang-tools-extra/clang-include-fixer/find-all-symbols/tool/run-find-all-symbols.py
 }
 
 build() {
     local _install="opt/${pkgbase%-opt}"
-    local _cmake_args=(
-        "-S" "${srcdir}/llvm-project-${_pkgver}.src/llvm"
+    local _common_options=(
         "-G" "Ninja"
         "-DCMAKE_BUILD_TYPE=Release"
         "-DCMAKE_INSTALL_PREFIX=/${_install}"
-        "-DLLVM_BINUTILS_INCDIR=/${_install}/include"
         "-DLLVM_APPEND_VC_REV=OFF"
-        "-DLLVM_VERSION_SUFFIX="
-        "-DLLVM_HOST_TRIPLE=${CHOST}"
-        "-DLLVM_ENABLE_RTTI=ON"
-        "-DLLVM_ENABLE_FFI=ON"
-        "-DFFI_INCLUDE_DIR:PATH=$(pkg-config --variable=includedir libffi)"
-        "-DLLVM_ENABLE_Z3_SOLVER=ON"
+    )
+    local _llvm_options=(
+        "-DCMAKE_SKIP_RPATH=ON"
+        "-DCLANG_DEFAULT_PIE_ON_LINUX=ON"
+        "-DCLANG_LINK_CLANG_DYLIB=ON"
+        "-DENABLE_LINKER_BUILD_ID=ON"
+        "-DLLVM_BINUTILS_INCDIR=/usr/include"
         "-DLLVM_BUILD_LLVM_DYLIB=ON"
-        "-DLLVM_LINK_LLVM_DYLIB=ON"
-        "-DLLVM_INSTALL_UTILS=ON"
-        "-DLLVM_BUILD_DOCS=ON"
-        "-DLLVM_ENABLE_DOXYGEN=OFF"
-        "-DLLVM_ENABLE_SPHINX=ON"
-        "-DSPHINX_OUTPUT_HTML:BOOL=OFF"
-        "-DSPHINX_WARNINGS_AS_ERRORS=OFF"
-        "-DLLVM_ENABLE_PROJECTS=polly;lldb;lld;compiler-rt;clang-tools-extra;clang"
-        "-DLLVM_ENABLE_DUMP=ON"
         "-DLLVM_ENABLE_BINDINGS=OFF"
+        "-DLLVM_ENABLE_CURL=ON"
+        "-DLLVM_ENABLE_FFI=ON"
+        "-DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;compiler-rt;lld;lldb;polly"
+        "-DLLVM_ENABLE_RTTI=ON"
+        "-DLLVM_ENABLE_Z3_SOLVER=ON"
+        "-DLLVM_HOST_TRIPLE=${CHOST}"
+        "-DLLVM_INCLUDE_BENCHMARKS=OFF"
+        "-DLLVM_INCLUDE_DOCS=OFF"
+        "-DLLVM_INCLUDE_EXAMPLES=OFF"
+        "-DLLVM_INSTALL_UTILS=ON"
+        "-DLLVM_LINK_LLVM_DYLIB=ON"
         "-DLLVM_POLLY_LINK_INTO_TOOLS=OFF"
+        "-DLLVM_USE_PERF=ON"
+    )
+    local _openmp_options=(
+        "-DCMAKE_MODULE_PATH=${srcdir}/build-llvm/lib/cmake"
+        "-DLIBOMP_INSTALL_ALIASES=OFF"
+        # Ignore OpenMP test failures and don't allow tests to stall for too long
+        "-DOPENMP_LIT_ARGS=-sv --ignore-fail --time-tests --timeout=300"
     )
     local _bootstrap_options=(
         "-DCMAKE_AR=/${_install}/bin/llvm-ar"
@@ -185,85 +204,107 @@ build() {
 
     export CFLAGS+=" ${CPPFLAGS}"
     export CXXFLAGS+=" ${CPPFLAGS}"
+    export LD_LIBRARY_PATH="${srcdir}/build-llvm/lib"
     if [[ -n ${_bootstrap} ]]; then
         export OLD_PATH="${PATH}"
         export PATH="/${_install}/bin:${PATH}"
-        export LD_LIBRARY_PATH="/${_install}/lib"
+        export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/${_install}/lib"
     fi
+    export PATH="${srcdir}/build-llvm/bin:${PATH}"
 
+    _cmake_args=("${_common_options[@]}" "${_llvm_options[@]}")
     [[ -n ${_bootstrap} ]] && _cmake_args+=("${_bootstrap_options[@]}")
-    cmake -B _build "${_cmake_args[@]}"
+    cmake -B build-llvm -S "llvm-project-${_pkgver}.src/llvm" "${_cmake_args[@]}"
 
-    pushd _build
     local distribution_components=$(_get_distribution_components | paste -sd\;)
     test -n "${distribution_components}"
     _cmake_args+=("-DLLVM_DISTRIBUTION_COMPONENTS=${distribution_components}")
-    popd
 
-    cmake -B _build "${_cmake_args[@]}" \
-        -D LLVM_LIT_ARGS="-sv --ignore-fail" \
-        -Wno-dev
-    ninja -C _build
+    cmake -B build-llvm -S "llvm-project-${_pkgver}.src/llvm" "${_cmake_args[@]}"
+    ninja -C build-llvm
+
+    # Build OpenMP separate from LLVM, but combine them later during packaging
+    _cmake_args=("${_common_options[@]}" "${_openmp_options[@]}")
+    [[ -n ${_bootstrap} ]] && _cmake_args+=("${_bootstrap_options[@]}")
+    cmake -B build-openmp -S "llvm-project-${_pkgver}.src/openmp" "${_cmake_args[@]}"
+    ninja -C build-openmp
 }
 
 check() {
-    # Arch does this for Clang/LLVM tests
-    export LD_LIBRARY_PATH="${srcdir}/_build/lib"
+    local _install="opt/${pkgbase%%-opt}"
+    local _py="$(_python_version)"
+
+    export LD_LIBRARY_PATH="${srcdir}/build-llvm/lib"
     if [[ -n ${_bootstrap} ]]; then
         export PATH="${OLD_PATH}"
+        # Allow LLVM Integrated Tester to be found for testing OpenMP
+        export PYTHONPATH="/${_install}/lib/python${_py}/site-packages"
         unset OLD_PATH
     fi
+    export PATH="${srcdir}/build-llvm/bin:${PATH}"
 
-    # Test failures are expected for LLDB
-    # For most of LLDB tests to work, one needs ptrace() to be unrestricted
-    for _project in llvm clang{,-tools} polly lld{,b}; do
-        ninja -C _build "check-${_project}"
-    done
+    ninja -C build-llvm check-llvm
+    ninja -C build-llvm check-clang
+    ninja -C build-llvm check-clang-tools
+    # Disable until buildgo.sh script is actually working for us
+    #ninja -C build-llvm check-compiler-rt || true
+    ninja -C build-llvm check-polly
+    ninja -C build-llvm check-lld
+    # Arch Linux upstream doesn't check LLDB they built, so don't allow LLDB
+    # test failures to block us from packaging the toolchain; tripping test(s)
+    # should be fixed with upstream commit(s). ptrace() must be unrestricted.
+    ninja -C build-llvm check-lldb || true
+
+    # Arch Linux upstream doesn't check OpenMP as well
+    ninja -C build-openmp check-libarcher
+    ninja -C build-openmp check-libomp
+    # All supported libomptarget tests fail to run
+    #ninja -C build-openmp check-libomptarget
+    ninja -C build-openmp check-ompt-multiplex
 }
 
 package() {
     local _install="opt/${pkgbase%%-opt}"
+    local _py="$(_python_version)"
 
-    DESTDIR="${pkgdir}" ninja -C _build install
+    DESTDIR="${pkgdir}" ninja -C build-llvm install-distribution
+    DESTDIR="${pkgdir}" ninja -C build-openmp install
+    cd "llvm-project-${_pkgver}.src"
 
     # Include lit for running lit-based tests in other projects
-    pushd "${srcdir}/llvm-project-${_pkgver}.src/llvm/utils/lit"
+    pushd llvm/utils/lit
     python3 setup.py install --root="${pkgdir}" --prefix="/${_install}" -O1
     popd
 
-    # Move analyzer scripts out of libexec
-    mv "${pkgdir}/${_install}"/libexec/{ccc,c++}-analyzer "${pkgdir}/${_install}/lib/clang/"
-    mv "${pkgdir}/${_install}"/libexec/analyze-{cc,c++} "${pkgdir}/${_install}/lib/clang/"
-    mv "${pkgdir}/${_install}"/libexec/intercept-{cc,c++} "${pkgdir}/${_install}/lib/clang/"
-    rmdir "$pkgdir/${_install}/libexec"
-    sed -i 's|libexec|lib/clang|' "${pkgdir}/${_install}/bin/scan-build"
+    # Move scanbuild-py into site-packages and install Python bindings
+    mv "${pkgdir}/${_install}"/lib/{libear,libscanbuild} \
+        "${pkgdir}/${_install}/lib/python${_py}/site-packages/"
+    cp -a clang/bindings/python/clang "${pkgdir}/${_install}/lib/python${_py}/site-packages/"
 
     # Symlink LLVMgold.so from lib/bfd-plugins
     # https://bugs.archlinux.org/task/28479
     install -d "${pkgdir}/${_install}/lib/bfd-plugins"
     ln -s ../LLVMgold.so "${pkgdir}/${_install}/lib/bfd-plugins/LLVMgold.so"
 
-    if [[ ${CARCH} == x86_64 ]]; then
-        # Needed for multilib (https://bugs.archlinux.org/task/29951)
-        # Header stub is taken from Fedora
-        mv "${pkgdir}/${_install}"/include/llvm/Config/llvm-config{,-64}.h
-        cp "${srcdir}/llvm-config.h" "${pkgdir}/${_install}/include/llvm/Config/llvm-config.h"
-    fi
+    # Move analyzer scripts out of /usr/libexec
+    mv "${pkgdir}/${_install}"/libexec/* "${pkgdir}/${_install}/lib/clang/"
+    rmdir "$pkgdir/${_install}/libexec"
+    sed -i 's|libexec|lib/clang|' \
+        "${pkgdir}/${_install}/bin/scan-build" \
+        "${pkgdir}/${_install}/lib/python${_py}/site-packages/libscanbuild/analyze.py"
 
-    pushd "${srcdir}/llvm-project-${_pkgver}.src"
+    # Compile Python scripts
+    _python_optimize "${pkgdir}/${_install}/share" \
+        "${pkgdir}/${_install}/lib/python${_py}/site-packages"
 
-    local _py=$(_python_version)
-    # Install Python bindings and optimize them
-    cp -a clang/bindings/python/clang "${pkgdir}/${_install}/lib/python${_py}/site-packages/"
-    _python_optimize "${pkgdir}/${_install}/lib/python${_py}/site-packages"
+    # Follow Arch Linux upstream into removing this static library
+    rm "${pkgdir}/${_install}/lib/libarcher_static.a"
 
-    # Optimize other Python files except 2 problem cases
-    _python_optimize "${pkgdir}/${_install}/share" -x 'clang-include-fixer|run-find-all-symbols'
+    # Make sure there are no manpages if we don't package docs
+    rm -r "${pkgdir}/${_install}/share/man"
 
-    for _project in llvm clang{,-tools-extra} compiler-rt lld{,b} polly; do
+    for _project in clang clang-tools-extra compiler-rt lld lldb llvm openmp polly; do
         install -Dm644 "${_project}/LICENSE.TXT" \
             "${pkgdir}/usr/share/licenses/${pkgname}/${_project}-LICENSE"
     done
-
-    popd
 }
