20230805 repository update
copy-to-esp-hook and dracut-hook-unified:
* Make ESP detection uniform across both available scripts.

diff --git a/build/copy-to-esp-hook/copy-to-esp b/build/copy-to-esp-hook/copy-to-esp
--- a/build/copy-to-esp-hook/copy-to-esp
+++ b/build/copy-to-esp-hook/copy-to-esp
@@ -13,20 +13,28 @@ copy-to-esp_install() {
 copy-to-esp_uninstall() {
     local efi_file=${1}
     rm "${esp_dir}/${efi_file}"
+    # Silently ignore folder removal if not empty
     rmdir --ignore-fail-on-non-empty "$(dirname "${esp_dir}/${efi_file}")"
 }
 
-if mountpoint -q /boot && [[ -d /boot/EFI ]]; then
-    echo "==> ESP mount point is at /boot or doesn't exist. Exiting."
+# vfat generally isn't case sensitive, so check /boot/efi/EFI before /boot/EFI
+if mountpoint -q /boot/efi && [[ -d /boot/efi/EFI ]]; then
+    esp_dir=/boot/efi
+# You probably won't need this script if your ESP is at /boot
+elif mountpoint -q /boot && [[ -d /boot/EFI ]]; then
+    echo "==> ESP mount point is at /boot. Exiting."
     exit 0
+# Check for /efi/EFI last since systemd might mount ESP at /efi
 elif mountpoint -q /efi && [[ -d /efi/EFI ]]; then
     esp_dir=/efi
-elif mountpoint -q /boot/efi && [[ -d /boot/efi/EFI ]]; then
-    esp_dir=/boot/efi
+else
+    echo "==> Unable to determine ESP mount point; perhaps not mounted?"
+    exit 1
 fi
 
 while read -r line; do
     efi_file=${line#boot/}
+    # Only handle EFI executables installed by pacman
     pacman -Qo "/boot/${efi_file}" >/dev/null 2>&1 || continue
     eval "copy-to-esp_${action} ${efi_file}"
 done
diff --git a/build/dracut-hook-unified/dracut b/build/dracut-hook-unified/dracut
--- a/build/dracut-hook-unified/dracut
+++ b/build/dracut-hook-unified/dracut
@@ -6,7 +6,7 @@
 kernels=()
 build_all=false
 build_uki=false
-esp_directory=/boot/EFI
+esp_directory=
 action=${1}
 
 dracut_install() {
@@ -66,12 +66,21 @@ if grep -q -P '^uefi=(\")?yes(\")?' /etc/dracut.conf.d/*; then
     build_uki=true
 fi
 
-# Install UKIs to /efi/EFI or /boot/efi/EFI if available
-# Default if neither matches: /boot/EFI
-if mountpoint -q /efi && [[ -d /efi/EFI ]]; then
-    esp_directory=/efi/EFI
-elif mountpoint -q /boot/efi && [[ -d /boot/efi/EFI ]]; then
-    esp_directory=/boot/efi/EFI
+# For UKIs, try to determine ESP directory
+if ${build_uki}; then
+    # vfat generally isn't case sensitive, so check /boot/efi/EFI before /boot/EFI
+    if mountpoint -q /boot/efi && [[ -d /boot/efi/EFI ]]; then
+        esp_directory=/boot/efi/EFI
+    # /boot/EFI should be default when nothing else matches, but blame systemd
+    elif mountpoint -q /boot && [[ -d /boot/EFI ]]; then
+        esp_directory=/boot/EFI
+    # Check for /efi/EFI last since systemd might mount ESP at /efi
+    elif mountpoint -q /efi && [[ -d /efi/EFI ]]; then
+        esp_directory=/efi/EFI
+    else
+        echo "==> uefi=\"yes\" detected in config, but unable to determine ESP mount point; perhaps not mounted?"
+        exit 1
+    fi
 fi
 
 for kernel in "${kernels[@]}"; do
